_BASE_: "Base-CenterMask-ResNet.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 2
  FCOS:
    NUM_CLASSES: 2
    PRE_NMS_TOPK_TRAIN: 100
    PRE_NMS_TOPK_TEST: 100
    POST_NMS_TOPK_TRAIN: 5
    POST_NMS_TOPK_TEST: 3
#    MIN_SIZE: 10
    MAX_SIZE: 120
#  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
#  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"
  WEIGHTS: "https://cloudstor.aarnet.edu.au/plus/s/glqFc13cCoEyHYy/download"
  RESNETS:
    DEPTH: 50
SOLVER:
#  IMS_PER_BATCH: 2
#  BASE_LR: 0.0025
#  WEIGHT_DECAY: 0.0001
#  STEPS: (0, 3097, 4360)
#  MAX_ITER: 6195 # 5 epocas
  LR_SCHEDULER_NAME: WarmupCosineLR
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: (0, 12287, 19656)
  MAX_ITER: 24575 # 5 epocas
#DATASETS:
#  TRAIN: ("CVC_HDClassif","CVC_ColonDB","CVC_ClinicDB",)
#  TEST: ("CVC_VideoClinicDB_test",)
DATASETS:
  TRAIN: ("CVC_VideoClinicDB_train", )
  TEST: ("CVC_VideoClinicDB_test",)
INPUT:
  MIN_SIZE_TRAIN: (288,)
  MAX_SIZE_TRAIN: 800
  MIN_SIZE_TEST: 288
  MAX_SIZE_TEST: 800
OUTPUT_DIR: "output/CenterMask-R-50-FPN-ms-3x_video"
TEST:
  DETECTIONS_PER_IMAGE: 1